In [12]:
import cv2
import numpy as np

In [2]:
img = cv2.imread("C:\\Users\\SHYAM\\Downloads\\parrot.jpg") 
print(img)

[[[55 89 42]
  [49 83 36]
  [45 75 32]
  ...
  [ 5 10 13]
  [ 5 10 13]
  [ 5 10 13]]

 [[46 80 33]
  [48 82 35]
  [51 81 38]
  ...
  [ 5 10 13]
  [ 5 10 13]
  [ 5 10 13]]

 [[49 83 36]
  [47 81 34]
  [46 76 33]
  ...
  [ 5 10 13]
  [ 5 10 13]
  [ 5 10 13]]

 ...

 [[ 3 11  4]
  [ 1  9  2]
  [ 2 10  3]
  ...
  [16 25 12]
  [18 27 14]
  [14 23 10]]

 [[ 3 11  4]
  [ 0  8  1]
  [ 0  8  1]
  ...
  [16 26 10]
  [17 26 13]
  [14 23 10]]

 [[ 0  8  1]
  [ 0  8  1]
  [ 0  8  1]
  ...
  [17 27 11]
  [16 26 10]
  [14 24  8]]]


In [10]:
# convert BGR format to Grayscale
img_g = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

cv2.imshow('frame1', img)
cv2.imshow('frame2', img_g)

# press any key with 0 wait time
cv2.waitKey(0)
# Close all imageframe
cv2.destroyAllWindows()

In [11]:
# Canny(image, threshold1, threshold2)
# Computing Edge Gradient with canny thresholds
# The edge gradients that are greater tha threshold value will be detected as Edges
# thresholds lower than threshold1 will not be considered as edges.
edges_low = cv2.Canny(img_g, 50, 120)
cv2.imshow('Edge Detection', edges_low)

edges_high = cv2.Canny(img_g, 60, 200)
cv2.imshow('High Edge Detection', edges_high)

# press any key with 0 wait time
cv2.waitKey(0)
# Close all imageframe
cv2.destroyAllWindows()

In [13]:
# Apply smoothening of Image - Apply Blur

# Blur using Filter2D
kernel = np.ones((5,5), np.float32) / 25
print(kernel)

[[0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]]


In [14]:
# Filter2D
smoothed = cv2.filter2D(img, -1, kernel)

In [15]:
# Average Blur
img_blur = cv2.blur(img, (5,5))

In [16]:
# Median Blur
m_blur = cv2.medianBlur(img, 7)

In [17]:
# Gaussian Blur, sigmaX(stdDev)= 1
g_blur = cv2.GaussianBlur(img, (7,7), 1)

In [19]:
cv2.imshow('Original', img)
cv2.imshow('Blur', smoothed)
cv2.imshow('average', img_blur)
cv2.imshow('median', m_blur)
cv2.imshow('gaussian', g_blur)

# press any key with 0 wait time
cv2.waitKey(0)
# Close all imageframe
cv2.destroyAllWindows()