In [1]:
import cv2
import random

In [2]:
def noise_black_white(image):
    # Get the dimensions of Image
    row, col = image.shape
    num_of_pixels = random.randint(1500, 20000)
    for i in range(num_of_pixels):
        # pick random y-coordinate
        y_coordinate = random.randint(0, row - 1)
        # pick random x-coordinate
        x_coordinate = random.randint(0, col - 1)
        image[y_coordinate][x_coordinate] = 255
    for i in range(num_of_pixels):
        # pick random y-coordinate
        y_coordinate = random.randint(0, row - 1)
        # pick random x-coordinate
        x_coordinate = random.randint(0, col - 1)
        image[y_coordinate][x_coordinate] = 0
    return image

In [3]:
image = cv2.imread("C:\\Users\\SHYAM\\Downloads\\parrot.jpg", cv2.IMREAD_GRAYSCALE)

In [4]:
cv2.imshow('Original Image', image)
cv2.imshow('Noisy Image',noise_black_white(image))

cv2.imwrite("E:/OpenCV/noisy_image.jpg",noise_black_white(image))

# press any key with 0 wait time
cv2.waitKey(0)
# Close all imageframe
cv2.destroyAllWindows()

In [6]:
# Median Blur
m_blur = cv2.medianBlur(image, 3)

# Gaussian Blur, sigmaX(stdDev)= 1
g_blur = cv2.GaussianBlur(image, (7,7), 1)

cv2.imshow('Original', image)
cv2.imshow('median', m_blur)
cv2.imshow('gaussian', g_blur)


# press any key with 0 wait time
cv2.waitKey(0)
# Close all imageframe
cv2.destroyAllWindows()

In [ ]:
import numpy as np

circles = np.zeros((4,2), int)
counter = 0

def mousePosition(event, x, y, flags, params):
    global counter
    if event == cv2.EVENT_LBUTTONDOWN:
        circles[counter] = x, y
        counter += 1
        print(circles)
        
cv2.imshow("Original", image)
cv2.setMouseCallback('Original', mousePosition)

# press any key with 0 wait time
cv2.waitKey(0)
# Close all imageframe
cv2.destroyAllWindows()

[[468 227]
 [  0   0]
 [  0   0]
 [  0   0]]
[[468 227]
 [252 174]
 [  0   0]
 [  0   0]]
[[468 227]
 [252 174]
 [128 189]
 [  0   0]]
[[468 227]
 [252 174]
 [128 189]
 [286 110]]


IndexError: index 4 is out of bounds for axis 0 with size 4

IndexError: index 4 is out of bounds for axis 0 with size 4

IndexError: index 4 is out of bounds for axis 0 with size 4

IndexError: index 4 is out of bounds for axis 0 with size 4

IndexError: index 4 is out of bounds for axis 0 with size 4

IndexError: index 4 is out of bounds for axis 0 with size 4

IndexError: index 4 is out of bounds for axis 0 with size 4

IndexError: index 4 is out of bounds for axis 0 with size 4

IndexError: index 4 is out of bounds for axis 0 with size 4